---
title: "Contents"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

- [Data preparation](0-preparation.html):
    - construct `SingleCellExperiment`
    - diagnostic plots
    - `FlowSom` & `ConsensusClusterPlus` (meta)clustering
    - dimensionality reduction (UMAP & t-SNE)
    
- [Clustering analysis](1-clustering.html):
    - Over cluster to 25 clusters
    - Heatmaps and tSNE plots of target expression to guide manual merging
    - Manual merging to identify main liver cell populations
    - Heatmaps with target expression in main cell populations 
    
- [Dimensionality reduction](2-dimred.html):
    - tSNE plots colored by patient/condition/cluster
    - tSNE plots colored by Target expression and split by condition
    
- [Differential analysis](3-differential.html):
    - Differential Abundance analysis with main liver populations
    - Differential State analysis with main liver populations
    
- [Granulocytes](4-granulos.html):
    - Cell counts/heatmaps/tSNE/clustering
    - DA/DS
    
- [Kupffer cells](5-KCs.html):
    - Cell counts/heatmaps/tSNE/clustering
    - DA/DS
 
- [Bone marrow derived macrophages](6-BMDM.html):
    - Cell counts/heatmaps/tSNE/clustering
    - DA/DS
